"""Runtime-inert SocratesZero research surface.

Importing this package has no runtime side effects and does not enable search.
It exposes immutable contracts, the explicit fixed-rotation baseline strategy,
deterministic legal-action machinery, and model-free advisory policy/value
baselines plus deterministic runtime-inert strategy baselines. The default CED
path remains the only execution path.
"""

from .contracts import (
    SEARCH_CONTRACT_SCHEMA_VERSION,
    ActionGenerator,
    ActionKind,
    ActionParameter,
    ActionPrior,
    ActionStatistics,
    ActionSuccessor,
    ActionTargetKind,
    BudgetExceeded,
    BudgetUsage,
    ContractValidationError,
    LegalAction,
    MoveHistoryRef,
    ObservationRef,
    PolicyContextEntry,
    PolicyPrior,
    RoleHistoryRef,
    SearchBudget,
    SearchConstitution,
    SearchReceipt,
    SearchResult,
    SearchState,
    SearchStrategy,
    SearchTerminationReason,
    SemanticArtifactRef,
    SuccessorStateEvaluator,
    TerminalStatus,
    ValueEstimator,
    canonical_json,
    stable_contract_id,
    validate_action_references,
)
from .baseline import (
    FIXED_ROTATION_BASELINE_ADAPTER_VERSION,
    FixedRotationBaselineAdapter,
    FixedRotationBaselineStrategy,
)
from .constitution import (
    LEGAL_ACTION_GENERATOR_VERSION,
    LEGAL_ACTION_VOCABULARY_VERSION,
    CEDSearchConstitution,
    DeterministicLegalActionGenerator,
)
from .policy import (
    HEURISTIC_POLICY_MIN_PROBABILITY,
    HEURISTIC_POLICY_PRIOR_VERSION,
    UNIFORM_POLICY_PRIOR_VERSION,
    HeuristicPolicyPrior,
    PolicyActionAudit,
    PolicyAdjustment,
    UniformPolicyPrior,
)
from .strategy import (
    BEST_OF_N_CANDIDATE_COUNT_V0,
    BEST_OF_N_STRATEGY_VERSION,
    GREEDY_STRATEGY_VERSION,
    BestOfNStrategy,
    GreedyStrategy,
)
from .value import (
    HEURISTIC_VALUE_ESTIMATOR_VERSION,
    HEURISTIC_VALUE_RULES_V0,
    NEUTRAL_VALUE_ESTIMATOR_VERSION,
    VALUE_MAX,
    VALUE_MIN,
    HeuristicValueEstimator,
    NeutralValueEstimator,
    ValueAudit,
    ValueComponent,
)

SOCRATES_ZERO_ENABLED_ENV = "SOCRATES_ZERO_ENABLED"
SOCRATES_ZERO_DEFAULT_ENABLED = False

__all__ = [
    "SEARCH_CONTRACT_SCHEMA_VERSION",
    "BEST_OF_N_CANDIDATE_COUNT_V0",
    "BEST_OF_N_STRATEGY_VERSION",
    "FIXED_ROTATION_BASELINE_ADAPTER_VERSION",
    "LEGAL_ACTION_GENERATOR_VERSION",
    "LEGAL_ACTION_VOCABULARY_VERSION",
    "GREEDY_STRATEGY_VERSION",
    "HEURISTIC_POLICY_MIN_PROBABILITY",
    "HEURISTIC_POLICY_PRIOR_VERSION",
    "HEURISTIC_VALUE_ESTIMATOR_VERSION",
    "HEURISTIC_VALUE_RULES_V0",
    "NEUTRAL_VALUE_ESTIMATOR_VERSION",
    "UNIFORM_POLICY_PRIOR_VERSION",
    "VALUE_MAX",
    "VALUE_MIN",
    "SOCRATES_ZERO_DEFAULT_ENABLED",
    "SOCRATES_ZERO_ENABLED_ENV",
    "ActionGenerator",
    "ActionKind",
    "ActionParameter",
    "ActionPrior",
    "ActionStatistics",
    "ActionSuccessor",
    "ActionTargetKind",
    "BudgetExceeded",
    "BudgetUsage",
    "BestOfNStrategy",
    "ContractValidationError",
    "CEDSearchConstitution",
    "DeterministicLegalActionGenerator",
    "FixedRotationBaselineAdapter",
    "FixedRotationBaselineStrategy",
    "GreedyStrategy",
    "HeuristicPolicyPrior",
    "HeuristicValueEstimator",
    "LegalAction",
    "MoveHistoryRef",
    "NeutralValueEstimator",
    "ObservationRef",
    "PolicyContextEntry",
    "PolicyActionAudit",
    "PolicyAdjustment",
    "PolicyPrior",
    "RoleHistoryRef",
    "SearchBudget",
    "SearchConstitution",
    "SearchReceipt",
    "SearchResult",
    "SearchState",
    "SearchStrategy",
    "SearchTerminationReason",
    "SemanticArtifactRef",
    "SuccessorStateEvaluator",
    "TerminalStatus",
    "UniformPolicyPrior",
    "ValueAudit",
    "ValueComponent",
    "ValueEstimator",
    "canonical_json",
    "stable_contract_id",
    "validate_action_references",
]
