"""Parity matrix for the shared hardened receipt-persistence primitive.

Both domain wrappers - ConsultationReceiptStore and MicroSocraticReceiptStore -
must reach the SAME shared ``AtomicReceiptStore`` implementation and therefore
provide identical publication security, while each preserves its OWN domain
error type (ConsultationError vs MicroSocraticError) and receipt schema.

The exhaustive algorithm coverage lives in test_external_consultation_receipts.py
(58 tests through ConsultationReceiptStore); this file proves the kernel wrapper
is not a second implementation and that error-type separation holds, with a
concise parametrized security matrix over BOTH domains plus a real mixed
primary/fallback concurrency stress through the kernel wrapper.
"""

import asyncio
import builtins
import json
import os
import threading
from concurrent.futures import ThreadPoolExecutor

import pytest

from backend.dialogues import openclaw_receipts as core_mod
from backend.dialogues.openclaw_receipts import sha256_text
from backend.dialogues.openclaw_consultation import (
    ConsultationError,
    ConsultationPolicy,
    ConsultationReceiptStore,
    ExternalConsultationRequest,
    ExternalConsultationService,
    MockConsultationProvider,
    verify_receipt as verify_consultation_receipt,
)
from backend.dialogues.openclaw_socratic_kernel import (
    KernelPolicy,
    MicroSocraticError,
    MicroSocraticKernelService,
    MicroSocraticReceiptStore,
    MicroSocraticRequest,
    MockKernelProvider,
    verify_receipt as verify_kernel_receipt,
)

_NOW = "2026-07-11T00:00:00Z"
_EXP = "2026-07-11T01:00:00Z"
_RID = "parity-req"


def _consult_receipt(variant="v", request_id=_RID):
    req = ExternalConsultationRequest(
        request_id=request_id, requesting_agent_id="a",
        mode="independent_solver", consulted_provider="mock",
        consulted_model="m", consultation_relation="peer_model",
        question="q " + variant, purpose="p", max_tokens=64,
        timeout_seconds=5.0, created_at=_NOW, expires_at=_EXP)
    svc = ExternalConsultationService(ConsultationPolicy(), worker_id="w",
                                      clock=lambda: _NOW)
    return asyncio.run(svc.consult(req, MockConsultationProvider("mock"),
                                   now=_NOW)).receipt


def _kernel_receipt(variant="v", request_id=_RID):
    req = MicroSocraticRequest(
        request_id=request_id, agent_id="a", mode="standard", provider="mock",
        model="m", task="task " + variant, draft="draft", purpose="p",
        max_tokens=64, timeout_seconds=5.0, created_at=_NOW, expires_at=_EXP)
    svc = MicroSocraticKernelService(KernelPolicy(), worker_id="w",
                                     clock=lambda: _NOW)
    return asyncio.run(svc.check(req, MockKernelProvider("mock"),
                                 now=_NOW)).receipt


class _Domain:
    def __init__(self, name, store_cls, error_type, make_receipt):
        self.name = name
        self.store_cls = store_cls
        self.error_type = error_type
        self.make_receipt = make_receipt

    def __repr__(self):
        return self.name


CONSULT = _Domain("consultation", ConsultationReceiptStore, ConsultationError,
                  _consult_receipt)
KERNEL = _Domain("kernel", MicroSocraticReceiptStore, MicroSocraticError,
                 _kernel_receipt)
DOMAINS = [CONSULT, KERNEL]


# Literal records emitted by the historical domain builders before the shared
# persistence extraction (consultation 0031757, kernel 4ff8891). Expected
# digests are deliberately frozen rather than regenerated by current builders.
_LEGACY_CONSULTATION_RECEIPT = {
    "schema_version": "openclaw_external_consultation_receipt_v1",
    "request_id": "legacy-consultation-fixture",
    "request_digest":
        "ea29c89aa89c74146731b3ab1bee7ff90fce18c0fb111e8fba4b0a88c160c786",
    "result_digest":
        "0304e5198753b370e9b941fad5145e90be4ccebc7c22e96053d07ab6d1bd1918",
    "requesting_agent_id": "legacy_agent",
    "mode": "critic",
    "provider": "mock",
    "model": "mock-critic",
    "consultation_relation": "peer_model",
    "candidate_order": [],
    "worker_id": "legacy-worker",
    "isolated_session": True,
    "tools_disabled": True,
    "delegation_disabled": True,
    "started_at": "2026-07-01T00:00:01Z",
    "completed_at": "2026-07-01T00:00:02Z",
    "provider_status": "ok",
    "token_usage": {"prompt_tokens": 7, "completion_tokens": 11},
    "receipt_digest":
        "4c65486f3799d34089633e8b67ce79cd111c9e86adb75f0f4f2344f0f583dacc",
}

_LEGACY_KERNEL_RECEIPT = {
    "schema_version": "openclaw_micro_socratic_receipt_v1",
    "request_id": "legacy-kernel-fixture",
    "request_digest":
        "f50898a9df71036841cd90413df3677af11a82dc7b491325efe3c90b7e2c1fce",
    "result_digest":
        "d07b20bf4750489e507340f26a177e95161e35a23d4f8b00189cb4b95acc360e",
    "agent_id": "legacy_agent",
    "mode": "standard",
    "provider": "mock",
    "model": "mock-auditor",
    "decision": "revise",
    "worker_id": "legacy-worker",
    "isolated_check": True,
    "tools_executed": False,
    "consultation_executed": False,
    "inner_rounds": 1,
    "started_at": "2026-07-01T00:00:01Z",
    "completed_at": "2026-07-01T00:00:02Z",
    "provider_status": "ok",
    "token_usage": {"prompt_tokens": 5, "completion_tokens": 9},
    "receipt_digest":
        "5b1851f6d07e4b7d6750d90e647a0c1cfce9d28e81223da5f07e6ea90e31e3ba",
}

_LEGACY_CASES = [
    pytest.param(
        CONSULT, _LEGACY_CONSULTATION_RECEIPT, verify_consultation_receipt,
        "consultation receipt digest mismatch", id="consultation"),
    pytest.param(
        KERNEL, _LEGACY_KERNEL_RECEIPT, verify_kernel_receipt,
        "kernel receipt digest mismatch", id="kernel"),
]


class _FakeClock:
    def __init__(self):
        self.now = 0.0

    def monotonic(self):
        return self.now

    def sleep(self, delay):
        self.now += delay


def _hashed():
    return sha256_text(_RID) + ".receipt.json"


def _receipt_bytes(receipt):
    return (json.dumps(receipt, ensure_ascii=False, sort_keys=True, indent=2)
            + "\n").encode("utf-8")


def _no_artifacts(tmp_path):
    names = [p.name for p in tmp_path.iterdir()]
    assert not any(n.endswith((".tmp", ".lock")) for n in names), names
    return names


def _exact_names(directory, expected):
    names = sorted(path.name for path in directory.iterdir())
    assert names == sorted(expected)
    return names


def _assert_safe_domain_error(excinfo, dom, directory):
    assert type(excinfo.value) is dom.error_type
    message = str(excinfo.value)
    assert message
    assert os.fspath(directory) not in message
    assert "simulated sensitive filesystem detail" not in message


_FIXED_TEMP_HEX = "0123456789abcdef0123456789abcdef"


class _FaultingTempHandle:
    """Real exclusive temp handle with one injected post-create failure."""

    def __init__(self, handle, state, *, fail_write=False, fail_close=False):
        self._handle = handle
        self._state = state
        self._fail_write = fail_write
        self._fail_close = fail_close

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        self.close()
        return False

    def __getattr__(self, name):
        return getattr(self._handle, name)

    def write(self, payload):
        self._state["write_attempts"] += 1
        if self._fail_write:
            raise OSError(5, "simulated sensitive filesystem detail")
        return self._handle.write(payload)

    def flush(self):
        self._state["flush_attempts"] += 1
        return self._handle.flush()

    def close(self):
        self._state["close_attempts"] += 1
        self._handle.close()  # close the real descriptor before reporting error
        if self._fail_close:
            raise OSError(5, "simulated sensitive filesystem detail")


def _install_temp_fault(monkeypatch, *, fail_write=False, fail_close=False):
    real_open = builtins.open
    state = {
        "write_attempts": 0,
        "flush_attempts": 0,
        "close_attempts": 0,
        "raw_handles": [],
    }

    class _FixedUUID:
        hex = _FIXED_TEMP_HEX

    def faulting_open(file, mode="r", *args, **kwargs):
        handle = real_open(file, mode, *args, **kwargs)
        if mode == "x" and os.fspath(file).endswith(".receipt.tmp"):
            state["raw_handles"].append(handle)
            return _FaultingTempHandle(
                handle, state, fail_write=fail_write, fail_close=fail_close)
        return handle

    monkeypatch.setattr(core_mod.uuid, "uuid4", lambda: _FixedUUID())
    monkeypatch.setattr(builtins, "open", faulting_open)
    return state, f".{_FIXED_TEMP_HEX}.receipt.tmp"


def _trace_save_deadline(monkeypatch, store):
    seen = {"acquire": [], "reconcile": []}
    real_acquire = store._acquire_lock
    real_reconcile = store._reconcile

    def traced_acquire(lock, path, deadline):
        seen["acquire"].append(deadline)
        return real_acquire(lock, path, deadline)

    def traced_reconcile(path, verified, *, deadline=None):
        seen["reconcile"].append(deadline)
        return real_reconcile(path, verified, deadline=deadline)

    monkeypatch.setattr(store, "_acquire_lock", traced_acquire)
    monkeypatch.setattr(store, "_reconcile", traced_reconcile)
    return seen


# --------------------------------------------------------------------------- #
# both wrappers reach ONE shared implementation
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_both_wrappers_subclass_the_shared_primitive(dom):
    assert issubclass(dom.store_cls, core_mod.AtomicReceiptStore)
    assert dom.store_cls._error_type is dom.error_type


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_both_wrappers_inherit_shared_persistence_methods_by_identity(dom):
    assert dom.store_cls.save is core_mod.AtomicReceiptStore.save
    assert dom.store_cls.load is core_mod.AtomicReceiptStore.load
    assert dom.store_cls.all_receipts is core_mod.AtomicReceiptStore.all_receipts


# --------------------------------------------------------------------------- #
# core persistence semantics, parametrized over both domains
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_first_save_then_idempotent_then_conflict(dom, tmp_path):
    store = dom.store_cls(tmp_path)
    a = dom.make_receipt("A")
    path = store.save(a)
    assert store.save(a) == path                       # idempotent
    conflicting = dom.make_receipt("B")
    assert conflicting["request_id"] == a["request_id"]
    with pytest.raises(dom.error_type, match="conflicting"):
        store.save(conflicting)                        # DOMAIN error type
    assert store.load(_RID)["receipt_digest"] == a["receipt_digest"]
    assert _no_artifacts(tmp_path) == [_hashed()]


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_digest_verification_enforced(dom, tmp_path):
    store = dom.store_cls(tmp_path)
    receipt = dict(dom.make_receipt("A"))
    receipt["provider"] = "tampered"                   # breaks receipt_digest
    with pytest.raises(dom.error_type):
        store.save(receipt)


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
@pytest.mark.parametrize("data,label", [
    (b"not json at all", "malformed-json"),
    (b"\xff\xfe\x00bad", "invalid-utf8"),
    (json.dumps({"unexpected": "shape"}).encode(), "invalid-schema"),
])
def test_malformed_final_load_is_domain_error(dom, tmp_path, data, label):
    store = dom.store_cls(tmp_path)
    path = store._path_for(_RID)
    tmp_path.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    with pytest.raises(dom.error_type):
        store.load(_RID)
    with pytest.raises(dom.error_type):
        store.all_receipts()


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_all_receipts_deterministic_order(dom, tmp_path):
    store = dom.store_cls(tmp_path)
    store.save(dom.make_receipt("one", request_id="alpha"))
    store.save(dom.make_receipt("two", request_id="bravo"))
    got = store.all_receipts()
    assert len(got) == 2
    expected = sorted([sha256_text("alpha"), sha256_text("bravo")])
    assert [sha256_text(r["request_id"]) for r in got] == expected


# --------------------------------------------------------------------------- #
# error-type separation (the generic primitive leaks neither domain's error)
# --------------------------------------------------------------------------- #

def test_error_types_do_not_cross_domains(tmp_path):
    c = ConsultationReceiptStore(tmp_path / "c")
    k = MicroSocraticReceiptStore(tmp_path / "k")
    # consultation conflict -> ConsultationError, never MicroSocraticError
    c.save(_consult_receipt("A"))
    with pytest.raises(ConsultationError):
        c.save(_consult_receipt("B"))
    # kernel conflict -> MicroSocraticError, never ConsultationError
    k.save(_kernel_receipt("A"))
    with pytest.raises(MicroSocraticError):
        k.save(_kernel_receipt("B"))
    # cross-check: neither raise is the other domain's error class
    assert not issubclass(ConsultationError, MicroSocraticError)
    assert not issubclass(MicroSocraticError, ConsultationError)


# --------------------------------------------------------------------------- #
# fault injection through the shared primitive, parametrized over both domains
# --------------------------------------------------------------------------- #

def _broken_link(src, dst):
    raise OSError("simulated: no hard-link support")


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_temp_write_failure_cleans_owned_temp_and_lock(
        dom, tmp_path, monkeypatch):
    state, _ = _install_temp_fault(monkeypatch, fail_write=True)
    store = dom.store_cls(tmp_path)

    with pytest.raises(dom.error_type) as excinfo:
        store.save(dom.make_receipt("temp-write-failure"))

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert "temp write failed" in str(excinfo.value)
    assert state["write_attempts"] == 1
    assert state["close_attempts"] >= 1
    assert state["raw_handles"] and all(
        handle.closed for handle in state["raw_handles"])
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_temp_close_failure_cleans_owned_temp_and_lock(
        dom, tmp_path, monkeypatch):
    state, _ = _install_temp_fault(monkeypatch, fail_close=True)
    store = dom.store_cls(tmp_path)

    with pytest.raises(dom.error_type) as excinfo:
        store.save(dom.make_receipt("temp-close-failure"))

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert "temp" in str(excinfo.value) and "failed" in str(excinfo.value)
    assert state["write_attempts"] == 1
    assert state["close_attempts"] >= 1
    assert state["raw_handles"] and all(
        handle.closed for handle in state["raw_handles"])
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_temp_write_and_unlink_failure_preserves_primary_and_cleans_lock(
        dom, tmp_path, monkeypatch):
    state, temp_name = _install_temp_fault(monkeypatch, fail_write=True)
    store = dom.store_cls(tmp_path)
    final_name = _hashed()
    lock_name = final_name.removesuffix(".json") + ".lock"
    real_unlink = core_mod.os.unlink
    unlink_attempts = []

    def selective_unlink(target):
        name = os.path.basename(os.fspath(target))
        unlink_attempts.append(name)
        if name == temp_name:
            raise OSError(5, "simulated sensitive filesystem detail", target)
        return real_unlink(target)

    monkeypatch.setattr(core_mod.os, "unlink", selective_unlink)
    with pytest.raises(dom.error_type) as excinfo:
        store.save(dom.make_receipt("temp-write-and-unlink-failure"))

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    message = str(excinfo.value)
    assert "temp write failed" in message
    assert "cleanup also failed" in message
    assert "temp-unlink OSError" in message
    assert state["close_attempts"] >= 1
    assert state["raw_handles"] and all(
        handle.closed for handle in state["raw_handles"])
    assert temp_name in unlink_attempts
    assert lock_name in unlink_attempts
    _exact_names(tmp_path, [temp_name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_temp_exclusive_open_oserror_is_safe_domain_error(
        dom, tmp_path, monkeypatch):
    real_open = builtins.open
    attempts = []

    def failing_temp_open(file, mode="r", *args, **kwargs):
        if mode == "x" and os.fspath(file).endswith(".receipt.tmp"):
            attempts.append(file)
            raise OSError(5, "simulated sensitive filesystem detail", file)
        return real_open(file, mode, *args, **kwargs)

    monkeypatch.setattr(builtins, "open", failing_temp_open)
    store = dom.store_cls(tmp_path)
    with pytest.raises(dom.error_type, match="temp creation failed") as excinfo:
        store.save(dom.make_receipt("temp-open-oserror"))
    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert len(attempts) == 1
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_lock_acquisition_generic_oserror_is_safe_domain_error(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    final = store._path_for(_RID)
    lock = store._lock_for(final)
    real_open = core_mod.os.open
    attempts = []

    def failing_lock_open(name, flags, *args):
        if os.fspath(name) == os.fspath(lock):
            attempts.append(os.fspath(name))
            raise OSError(5, "simulated sensitive filesystem detail", name)
        return real_open(name, flags, *args)

    monkeypatch.setattr(core_mod.os, "open", failing_lock_open)
    with pytest.raises(
            dom.error_type, match="lock acquisition failed") as excinfo:
        store.save(dom.make_receipt("lock-open-oserror"))
    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [os.fspath(lock)]
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
@pytest.mark.parametrize("exception_cls,error_number", [
    pytest.param(PermissionError, 13, id="permission"),
    pytest.param(OSError, 5, id="oserror"),
])
def test_save_mkdir_failure_is_safe_domain_error(
        dom, exception_cls, error_number, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    receipt = dom.make_receipt("mkdir-failure")
    path_type = type(store.directory)
    real_mkdir = path_type.mkdir
    attempts = []

    def failing_mkdir(current, *args, **kwargs):
        if current == store.directory:
            attempts.append(current)
            raise exception_cls(
                error_number, "simulated sensitive filesystem detail", current)
        return real_mkdir(current, *args, **kwargs)

    monkeypatch.setattr(path_type, "mkdir", failing_mkdir)
    with pytest.raises(dom.error_type) as excinfo:
        store.save(receipt)

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [store.directory]
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_save_base_directory_resolve_failure_is_safe_domain_error(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    receipt = dom.make_receipt("base-resolve-failure")
    path_type = type(store.directory)
    real_resolve = path_type.resolve
    attempts = []

    def failing_resolve(current, *args, **kwargs):
        if current == store.directory:
            attempts.append(current)
            raise OSError(
                5, "simulated sensitive filesystem detail", current)
        return real_resolve(current, *args, **kwargs)

    monkeypatch.setattr(path_type, "resolve", failing_resolve)
    with pytest.raises(dom.error_type) as excinfo:
        store.save(receipt)

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [store.directory]
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_save_final_containment_resolve_failure_is_safe_domain_error(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    receipt = dom.make_receipt("containment-resolve-failure")
    path_type = type(store.directory)
    real_resolve = path_type.resolve
    base = store.directory.resolve()
    final = base / _hashed()
    attempts = []

    def failing_resolve(current, *args, **kwargs):
        if current == final:
            attempts.append(current)
            raise OSError(
                5, "simulated sensitive filesystem detail", current)
        return real_resolve(current, *args, **kwargs)

    monkeypatch.setattr(path_type, "resolve", failing_resolve)
    with pytest.raises(dom.error_type) as excinfo:
        store.save(receipt)

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [final]
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_request_id_validation_error_precedes_filesystem_resolution(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    with pytest.raises(dom.error_type) as expected:
        store._clean_request_id("../escape")

    def resolve_must_not_run(current, *args, **kwargs):
        pytest.fail("filesystem resolution ran after request_id validation failed")

    monkeypatch.setattr(type(store.directory), "resolve", resolve_must_not_run)
    with pytest.raises(dom.error_type) as actual:
        store._path_for("../escape")
    assert type(actual.value) is dom.error_type
    assert str(actual.value) == str(expected.value)
    _exact_names(tmp_path, [])


# Strict public discovery must distinguish true absence from inspection denial.

@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_load_genuinely_missing_final_returns_none(dom, tmp_path):
    store = dom.store_cls(tmp_path)
    assert store.load(_RID) is None
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
@pytest.mark.parametrize("exception_cls,error_number", [
    pytest.param(PermissionError, 13, id="permission"),
    pytest.param(OSError, 5, id="oserror"),
])
def test_load_final_stat_failure_is_safe_domain_error(
        dom, exception_cls, error_number, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    final = store._path_for(_RID)

    # _path_for()/containment resolution has separate coverage; this test
    # isolates final existence-discovery failure and avoids platform-dependent
    # Path.resolve() stat behavior on Windows.
    def fixed_path_for(request_id):
        assert request_id == _RID
        return final

    monkeypatch.setattr(store, "_path_for", fixed_path_for)
    path_type = type(final)
    real_stat = path_type.stat
    attempts = []

    def failing_stat(current, *args, **kwargs):
        if current == final:
            attempts.append(current)
            raise exception_cls(
                error_number, "simulated sensitive filesystem detail", current)
        return real_stat(current, *args, **kwargs)

    monkeypatch.setattr(path_type, "stat", failing_stat)
    with pytest.raises(dom.error_type) as excinfo:
        store.load(_RID)

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [final]
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_load_final_read_permission_error_is_safe_domain_error(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    receipt = dom.make_receipt("load-read-denial")
    path = store.save(receipt)
    final_bytes = path.read_bytes()
    path_type = type(path)
    real_read = path_type.read_text
    attempts = []

    def denied_read(current, *args, **kwargs):
        if current == path:
            attempts.append(current)
            raise PermissionError(
                13, "simulated sensitive filesystem detail", current)
        return real_read(current, *args, **kwargs)

    monkeypatch.setattr(path_type, "read_text", denied_read)
    with pytest.raises(dom.error_type) as excinfo:
        store.load(_RID)

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [path]
    assert path.read_bytes() == final_bytes
    _exact_names(tmp_path, [path.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_all_receipts_genuinely_missing_directory_returns_empty(
        dom, tmp_path):
    directory = tmp_path / "genuinely-missing"
    store = dom.store_cls(directory)
    assert store.all_receipts() == []
    assert not directory.is_dir()
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
@pytest.mark.parametrize("exception_cls,error_number", [
    pytest.param(PermissionError, 13, id="permission"),
    pytest.param(OSError, 5, id="oserror"),
])
def test_all_receipts_directory_stat_failure_is_safe_domain_error(
        dom, exception_cls, error_number, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    path_type = type(store.directory)
    real_stat = path_type.stat
    attempts = []

    def failing_stat(current, *args, **kwargs):
        if current == store.directory:
            attempts.append(current)
            raise exception_cls(
                error_number, "simulated sensitive filesystem detail", current)
        return real_stat(current, *args, **kwargs)

    monkeypatch.setattr(path_type, "stat", failing_stat)
    with pytest.raises(dom.error_type) as excinfo:
        store.all_receipts()

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [store.directory]
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
@pytest.mark.parametrize("exception_cls,error_number", [
    pytest.param(PermissionError, 13, id="permission"),
    pytest.param(OSError, 5, id="oserror"),
])
def test_all_receipts_enumeration_failure_is_safe_domain_error(
        dom, exception_cls, error_number, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    real_scandir = core_mod.os.scandir
    attempts = []

    def failing_scandir(current):
        if os.fspath(current) == os.fspath(store.directory):
            attempts.append(current)
            raise exception_cls(
                error_number, "simulated sensitive filesystem detail", current)
        return real_scandir(current)

    monkeypatch.setattr(core_mod.os, "scandir", failing_scandir)
    with pytest.raises(dom.error_type) as excinfo:
        store.all_receipts()

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert attempts == [store.directory]
    monkeypatch.setattr(core_mod.os, "scandir", real_scandir)
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
@pytest.mark.parametrize("exception_cls,error_number", [
    pytest.param(PermissionError, 13, id="permission"),
    pytest.param(OSError, 5, id="oserror"),
])
def test_all_receipts_iteration_failure_is_safe_domain_error(
        dom, exception_cls, error_number, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    real_scandir = core_mod.os.scandir
    iterations = []

    class _FailingEntries:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, traceback):
            return False

        def __iter__(self):
            return self

        def __next__(self):
            iterations.append(1)
            raise exception_cls(
                error_number, "simulated sensitive filesystem detail")

    def failing_iteration(current):
        if os.fspath(current) == os.fspath(store.directory):
            return _FailingEntries()
        return real_scandir(current)

    monkeypatch.setattr(core_mod.os, "scandir", failing_iteration)
    with pytest.raises(dom.error_type) as excinfo:
        store.all_receipts()

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert iterations == [1]
    monkeypatch.setattr(core_mod.os, "scandir", real_scandir)
    _exact_names(tmp_path, [])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
@pytest.mark.parametrize("data", [
    pytest.param(b"not json at all", id="malformed-json"),
    pytest.param(b"\xff\xfe\x00bad", id="invalid-utf8"),
])
def test_all_receipts_discovered_bad_bytes_is_safe_domain_error(
        dom, data, tmp_path):
    store = dom.store_cls(tmp_path)
    path = store._path_for(_RID)
    path.write_bytes(data)

    with pytest.raises(dom.error_type) as excinfo:
        store.all_receipts()

    _assert_safe_domain_error(excinfo, dom, tmp_path)
    _exact_names(tmp_path, [path.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_all_receipts_discovery_is_deterministically_sorted(dom, tmp_path):
    store = dom.store_cls(tmp_path)
    receipts = [
        dom.make_receipt("third", request_id="charlie"),
        dom.make_receipt("first", request_id="alpha"),
        dom.make_receipt("second", request_id="bravo"),
    ]
    expected = sorted(receipts, key=lambda item: sha256_text(item["request_id"]))
    for receipt in reversed(receipts):
        store._path_for(receipt["request_id"]).write_text(
            json.dumps(receipt), encoding="utf-8")

    assert store.all_receipts() == expected
    _exact_names(tmp_path, [
        f"{sha256_text(receipt['request_id'])}.receipt.json"
        for receipt in receipts
    ])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_transient_lock_permission_error_retries(dom, tmp_path, monkeypatch):
    monkeypatch.setattr(core_mod.os, "link", _broken_link)
    store = dom.store_cls(tmp_path, lock_timeout=1.0, lock_poll=0.1)
    receipt = dom.make_receipt("A")
    lock = store._lock_for(store._path_for(_RID))
    real_open = core_mod.os.open
    clock = _FakeClock()
    attempts = []

    def transient_open(name, flags):
        assert os.fspath(name) == os.fspath(lock)
        attempts.append(name)
        if len(attempts) <= 3:
            raise PermissionError(13, "DELETE_PENDING", name)
        return real_open(name, flags)

    monkeypatch.setattr(core_mod, "time", clock)
    monkeypatch.setattr(core_mod.os, "open", transient_open)
    assert store.save(receipt) == store._path_for(_RID)
    assert len(attempts) == 4
    assert _no_artifacts(tmp_path) == [_hashed()]


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_permanent_lock_permission_error_bounded_domain_error(
        dom, tmp_path, monkeypatch):
    monkeypatch.setattr(core_mod.os, "link", _broken_link)
    store = dom.store_cls(tmp_path, lock_timeout=3.0, lock_poll=1.0)
    receipt = dom.make_receipt("A")
    lock = store._lock_for(store._path_for(_RID))
    tmp_path.mkdir(parents=True, exist_ok=True)
    lock.write_bytes(b"foreign")
    clock = _FakeClock()

    def denied_open(name, flags):
        raise PermissionError(13, "denied", name)

    monkeypatch.setattr(core_mod, "time", clock)
    monkeypatch.setattr(core_mod.os, "open", denied_open)
    with pytest.raises(dom.error_type, match="lock timed out"):
        store.save(receipt)
    assert clock.now == 3.0                            # one deadline, not reset
    assert lock.read_bytes() == b"foreign"             # foreign lock retained
    _exact_names(tmp_path, [lock.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_permanent_final_read_denial_bounded_domain_error(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path, lock_timeout=3.0, lock_poll=1.0)
    receipt = dom.make_receipt("A")
    store.save(receipt)
    path = store._path_for(_RID)
    final_bytes = path.read_bytes()
    clock = _FakeClock()
    path_type = type(path)
    real_read = path_type.read_text

    def denied(current, *a, **k):
        if current == path:
            raise PermissionError(13, "sharing", current)
        return real_read(current, *a, **k)

    monkeypatch.setattr(core_mod, "time", clock)
    monkeypatch.setattr(path_type, "read_text", denied)
    with pytest.raises(dom.error_type, match="timed out"):
        store.save(receipt)
    assert clock.now == 3.0
    assert path.read_bytes() == final_bytes            # final unchanged
    _exact_names(tmp_path, [path.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_transient_final_read_reconciliation_recovers_with_original_deadline(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path, lock_timeout=1.0, lock_poll=0.1)
    receipt = dom.make_receipt("transient-final-read")
    path = store._path_for(_RID)
    lock = store._lock_for(path)
    expected_bytes = _receipt_bytes(receipt)
    real_open = core_mod.os.open
    path_type = type(path)
    real_read = path_type.read_text
    clock = _FakeClock()
    opens = []
    read_times = []

    def acquire_then_peer_publishes(name, flags, *args):
        assert os.fspath(name) == os.fspath(lock)
        opens.append(clock.now)
        fd = real_open(name, flags, *args)
        path.write_bytes(expected_bytes)
        return fd

    def transient_read(current, *args, **kwargs):
        if current == path:
            read_times.append(clock.now)
            if len(read_times) <= 3:
                raise PermissionError(13, "transient sharing denial", current)
        return real_read(current, *args, **kwargs)

    deadlines = _trace_save_deadline(monkeypatch, store)
    monkeypatch.setattr(core_mod, "time", clock)
    monkeypatch.setattr(core_mod.os, "open", acquire_then_peer_publishes)
    monkeypatch.setattr(path_type, "read_text", transient_read)
    assert store.save(receipt) == path
    assert deadlines == {"acquire": [1.0], "reconcile": [1.0]}
    assert opens == [0.0]
    assert read_times == pytest.approx([0.0, 0.1, 0.2, 0.3])
    assert clock.now == pytest.approx(0.3)
    assert path.read_bytes() == expected_bytes
    _exact_names(tmp_path, [path.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_cross_phase_permanent_read_denial_uses_one_deadline(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path, lock_timeout=3.0, lock_poll=1.0)
    receipt = dom.make_receipt("cross-phase-permanent")
    path = store._path_for(_RID)
    expected_bytes = _receipt_bytes(receipt)
    clock = _FakeClock()
    open_times = []
    read_times = []
    path_type = type(path)
    real_read = path_type.read_text

    def contend_then_publish(name, flags, *args):
        open_times.append(clock.now)
        if len(open_times) == 2:
            path.write_bytes(expected_bytes)
        raise FileExistsError(17, "peer holds lock", name)

    def permanently_denied(current, *args, **kwargs):
        if current == path:
            read_times.append(clock.now)
            raise PermissionError(13, "final sharing denied", current)
        return real_read(current, *args, **kwargs)

    deadlines = _trace_save_deadline(monkeypatch, store)
    monkeypatch.setattr(core_mod, "time", clock)
    monkeypatch.setattr(core_mod.os, "open", contend_then_publish)
    monkeypatch.setattr(path_type, "read_text", permanently_denied)
    with pytest.raises(dom.error_type, match="reconciliation timed out"):
        store.save(receipt)

    assert deadlines == {"acquire": [3.0], "reconcile": [3.0]}
    assert open_times == [0.0, 1.0]
    assert read_times == [2.0]             # no read begins at/after the deadline
    assert clock.now == 3.0                # never reset to t=5 or t=6
    assert path.read_bytes() == expected_bytes
    _exact_names(tmp_path, [path.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_cross_phase_read_recovers_before_original_deadline(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path, lock_timeout=3.0, lock_poll=0.5)
    receipt = dom.make_receipt("cross-phase-recovery")
    path = store._path_for(_RID)
    expected_bytes = _receipt_bytes(receipt)
    clock = _FakeClock()
    open_times = []
    read_times = []
    path_type = type(path)
    real_read = path_type.read_text

    def contend_then_publish(name, flags, *args):
        open_times.append(clock.now)
        if len(open_times) == 4:
            path.write_bytes(expected_bytes)
        raise FileExistsError(17, "peer holds lock", name)

    def recover_before_deadline(current, *args, **kwargs):
        if current == path:
            read_times.append(clock.now)
            if len(read_times) == 1:
                raise PermissionError(13, "transient sharing denial", current)
        return real_read(current, *args, **kwargs)

    deadlines = _trace_save_deadline(monkeypatch, store)
    monkeypatch.setattr(core_mod, "time", clock)
    monkeypatch.setattr(core_mod.os, "open", contend_then_publish)
    monkeypatch.setattr(path_type, "read_text", recover_before_deadline)
    assert store.save(receipt) == path

    assert deadlines == {"acquire": [3.0], "reconcile": [3.0]}
    assert open_times == [0.0, 0.5, 1.0, 1.5]
    assert read_times == [2.0, 2.5]
    assert clock.now == 2.5
    assert path.read_bytes() == expected_bytes
    _exact_names(tmp_path, [path.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_poll_capped_and_no_post_deadline_op(dom, tmp_path, monkeypatch):
    monkeypatch.setattr(core_mod.os, "link", _broken_link)
    store = dom.store_cls(tmp_path, lock_timeout=1.0, lock_poll=10.0)
    receipt = dom.make_receipt("A")
    lock = store._lock_for(store._path_for(_RID))
    tmp_path.mkdir(parents=True, exist_ok=True)
    lock.write_bytes(b"foreign")
    clock = _FakeClock()
    opens = []

    def denied_open(name, flags):
        opens.append(name)
        raise PermissionError(13, "held", name)

    monkeypatch.setattr(core_mod, "time", clock)
    monkeypatch.setattr(core_mod.os, "open", denied_open)
    with pytest.raises(dom.error_type, match="lock timed out"):
        store.save(receipt)
    assert clock.now == 1.0                            # capped to remaining
    assert len(opens) == 1                             # no post-deadline acquire
    _exact_names(tmp_path, [lock.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_replace_failure_normalized(dom, tmp_path, monkeypatch):
    monkeypatch.setattr(core_mod.os, "link", _broken_link)

    def bad_replace(src, dst):
        raise PermissionError(13, "replace denied", dst)

    monkeypatch.setattr(core_mod.os, "replace", bad_replace)
    store = dom.store_cls(tmp_path)
    with pytest.raises(dom.error_type, match="publication failed"):
        store.save(dom.make_receipt("A"))
    assert _no_artifacts(tmp_path) == []               # no final, cleaned up


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_cleanup_lock_unlink_failure_normalized(dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    lock = store._lock_for(store._path_for(_RID))
    real_unlink = core_mod.os.unlink

    def sel_unlink(target):
        if os.fspath(target) == os.fspath(lock):
            raise OSError(13, "lock unlink denied", target)
        return real_unlink(target)

    monkeypatch.setattr(core_mod.os, "unlink", sel_unlink)
    with pytest.raises(dom.error_type, match="cleanup failed"):
        store.save(dom.make_receipt("A"))
    assert store.load(_RID)["receipt_digest"] == dom.make_receipt("A")[
        "receipt_digest"]                              # final valid & unchanged
    _exact_names(tmp_path, [_hashed(), lock.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_successful_publication_lock_close_failure_keeps_exact_final(
        dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    receipt = dom.make_receipt("lock-close-failure")
    real_close = core_mod.os.close
    close_attempts = []

    def close_then_report(fd):
        close_attempts.append(fd)
        real_close(fd)  # realistic: never leak the underlying descriptor
        raise OSError(9, "simulated sensitive filesystem detail")

    monkeypatch.setattr(core_mod.os, "close", close_then_report)
    with pytest.raises(dom.error_type, match="cleanup failed") as excinfo:
        store.save(receipt)
    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert "lock-close OSError" in str(excinfo.value)
    assert len(close_attempts) == 1
    _exact_names(tmp_path, [_hashed()])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_successful_publication_temp_unlink_failure_has_exact_artifacts(
        dom, tmp_path, monkeypatch):
    fixed = "abcdefabcdefabcdefabcdefabcdefab"

    class _FixedUUID:
        hex = fixed

    store = dom.store_cls(tmp_path)
    receipt = dom.make_receipt("temp-cleanup-failure")
    final = store._path_for(_RID)
    lock = store._lock_for(final)
    temp_name = f".{fixed}.receipt.tmp"
    real_unlink = core_mod.os.unlink
    unlink_attempts = []

    def selective_unlink(target):
        name = os.path.basename(os.fspath(target))
        unlink_attempts.append(name)
        if name == temp_name:
            raise OSError(5, "simulated sensitive filesystem detail", target)
        return real_unlink(target)

    monkeypatch.setattr(core_mod.uuid, "uuid4", lambda: _FixedUUID())
    monkeypatch.setattr(core_mod.os, "unlink", selective_unlink)
    with pytest.raises(dom.error_type, match="cleanup failed") as excinfo:
        store.save(receipt)
    _assert_safe_domain_error(excinfo, dom, tmp_path)
    assert "temp-unlink OSError" in str(excinfo.value)
    assert lock.name in unlink_attempts and temp_name in unlink_attempts
    verifier = verify_consultation_receipt if dom is CONSULT \
        else verify_kernel_receipt
    assert verifier(store.load(_RID)) == receipt
    _exact_names(tmp_path, [final.name, temp_name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_foreign_temp_collision_retained(dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    fixed = "deadbeefdeadbeefdeadbeefdeadbeef"

    class _U:
        hex = fixed

    monkeypatch.setattr(core_mod.uuid, "uuid4", lambda: _U())
    tmp_path.mkdir(parents=True, exist_ok=True)
    foreign = tmp_path / f".{fixed}.receipt.tmp"
    foreign.write_bytes(b"foreign-bytes")
    with pytest.raises(dom.error_type, match="temp allocation failed"):
        store.save(dom.make_receipt("A"))
    assert foreign.read_bytes() == b"foreign-bytes"    # never touched
    _exact_names(tmp_path, [foreign.name])


@pytest.mark.parametrize("dom", DOMAINS, ids=repr)
def test_primary_link_preferred_under_lock(dom, tmp_path, monkeypatch):
    store = dom.store_cls(tmp_path)
    order = []
    real_open, real_link = core_mod.os.open, core_mod.os.link

    def rec_open(name, flags):
        order.append("lock-open")
        return real_open(name, flags)

    def rec_link(src, dst):
        order.append("link")
        return real_link(src, dst)

    def no_replace(src, dst):
        pytest.fail("os.replace used despite working os.link")

    monkeypatch.setattr(core_mod.os, "open", rec_open)
    monkeypatch.setattr(core_mod.os, "link", rec_link)
    monkeypatch.setattr(core_mod.os, "replace", no_replace)
    store.save(dom.make_receipt("A"))
    assert order[0] == "lock-open" and "link" in order
    assert order.index("lock-open") < order.index("link")
    assert _no_artifacts(tmp_path) == [_hashed()]


# --------------------------------------------------------------------------- #
# backward compatibility: frozen pre-refactor records still load unchanged
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("dom,fixture,verifier,error_message", _LEGACY_CASES)
def test_frozen_pre_refactor_record_loads_and_verifies_unchanged(
        dom, fixture, verifier, error_message, tmp_path):
    receipt = json.loads(json.dumps(fixture))
    store = dom.store_cls(tmp_path)
    path = store.save(receipt)
    assert verifier(receipt) == receipt
    assert store.load(receipt["request_id"]) == receipt
    assert store.all_receipts() == [receipt]
    _exact_names(tmp_path, [path.name])


@pytest.mark.parametrize("dom,fixture,verifier,error_message", _LEGACY_CASES)
def test_frozen_pre_refactor_tamper_retains_domain_digest_error(
        dom, fixture, verifier, error_message, tmp_path):
    tampered = json.loads(json.dumps(fixture))
    tampered["provider"] = "tampered-provider"
    with pytest.raises(dom.error_type, match=f"^{error_message}$") as excinfo:
        verifier(tampered)
    assert type(excinfo.value) is dom.error_type
    _exact_names(tmp_path, [])


# --------------------------------------------------------------------------- #
# mixed primary/fallback concurrency through the KERNEL wrapper
# --------------------------------------------------------------------------- #

def _run_kernel_gated_mixed_race(
        store, winner_receipt, loser_receipt, *, winner_role, monkeypatch):
    loser_role = "primary" if winner_role == "fallback" else "fallback"
    real_open = core_mod.os.open
    real_link = core_mod.os.link
    real_replace = core_mod.os.replace
    thread_role = threading.local()
    winner_has_lock = threading.Event()
    loser_attempted_lock = threading.Event()
    counter_lock = threading.Lock()
    counters = {
        "capability": {"primary": 0, "fallback": 0},
        "lock": {"primary": 0, "fallback": 0},
        "link": {"primary": 0, "fallback": 0},
        "replace": {"primary": 0, "fallback": 0},
    }

    def bump(operation, role):
        with counter_lock:
            counters[operation][role] += 1

    def tracked_open(name, flags, *args):
        role = thread_role.value
        bump("lock", role)
        try:
            fd = real_open(name, flags, *args)
        except (FileExistsError, PermissionError):
            if role == loser_role and winner_has_lock.is_set():
                loser_attempted_lock.set()
            raise
        if role == winner_role:
            winner_has_lock.set()
        return fd

    def mixed_link(src, dst):
        role = thread_role.value
        bump("link", role)
        if role == "fallback":
            raise OSError("forced fallback capability")
        if role == winner_role and not loser_attempted_lock.wait(timeout=5):
            raise RuntimeError("loser never attempted the shared lock")
        return real_link(src, dst)

    def gated_replace(src, dst):
        role = thread_role.value
        bump("replace", role)
        if role == winner_role and not loser_attempted_lock.wait(timeout=5):
            raise RuntimeError("loser never attempted the shared lock")
        return real_replace(src, dst)

    monkeypatch.setattr(core_mod.os, "open", tracked_open)
    monkeypatch.setattr(core_mod.os, "link", mixed_link)
    monkeypatch.setattr(core_mod.os, "replace", gated_replace)
    results = {}

    def worker(label, role, receipt):
        thread_role.value = role
        bump("capability", role)
        try:
            store.save(receipt)
            results[label] = "WIN"
        except MicroSocraticError:
            results[label] = "CONFLICT"
        except Exception as exc:                        # noqa: BLE001
            results[label] = f"ERR:{type(exc).__name__}"

    winner = threading.Thread(
        target=worker,
        args=("winner", winner_role, winner_receipt),
        name=f"kernel-{winner_role}-winner",
    )
    loser = threading.Thread(
        target=worker,
        args=("loser", loser_role, loser_receipt),
        name=f"kernel-{loser_role}-loser",
    )
    winner.start()
    assert winner_has_lock.wait(timeout=5)
    loser.start()
    winner.join(timeout=10)
    loser.join(timeout=10)
    assert not winner.is_alive() and not loser.is_alive()
    assert loser_attempted_lock.is_set()
    assert counters["capability"] == {"primary": 1, "fallback": 1}
    assert counters["lock"][winner_role] == 1
    assert counters["lock"][loser_role] >= 1
    assert counters["link"][winner_role] == 1
    assert counters["link"][loser_role] == 0
    if winner_role == "fallback":
        assert counters["replace"] == {"primary": 0, "fallback": 1}
    else:
        assert counters["replace"] == {"primary": 0, "fallback": 0}
    return results, counters


def _assert_exact_kernel_final(store, expected, directory):
    path = store._path_for(expected["request_id"])
    final_bytes = path.read_bytes()
    assert verify_kernel_receipt(store.load(expected["request_id"])) == expected
    assert path.read_bytes() == final_bytes
    _exact_names(directory, [path.name])


def test_kernel_deterministic_fallback_first_conflict(tmp_path, monkeypatch):
    store = MicroSocraticReceiptStore(
        tmp_path, lock_timeout=2.0, lock_poll=0.001)
    fallback_winner = _kernel_receipt("fallback deterministic winner")
    primary_loser = _kernel_receipt("primary deterministic loser")
    results, counters = _run_kernel_gated_mixed_race(
        store, fallback_winner, primary_loser,
        winner_role="fallback", monkeypatch=monkeypatch)
    assert results == {"winner": "WIN", "loser": "CONFLICT"}
    assert counters["link"] == {"primary": 0, "fallback": 1}
    _assert_exact_kernel_final(store, fallback_winner, tmp_path)


def test_kernel_deterministic_primary_first_conflict(tmp_path, monkeypatch):
    store = MicroSocraticReceiptStore(
        tmp_path, lock_timeout=2.0, lock_poll=0.001)
    primary_winner = _kernel_receipt("primary deterministic winner")
    fallback_loser = _kernel_receipt("fallback deterministic loser")
    results, counters = _run_kernel_gated_mixed_race(
        store, primary_winner, fallback_loser,
        winner_role="primary", monkeypatch=monkeypatch)
    assert results == {"winner": "WIN", "loser": "CONFLICT"}
    assert counters["link"] == {"primary": 1, "fallback": 0}
    _assert_exact_kernel_final(store, primary_winner, tmp_path)


def test_kernel_deterministic_identical_mixed_paths(tmp_path, monkeypatch):
    store = MicroSocraticReceiptStore(
        tmp_path, lock_timeout=2.0, lock_poll=0.001)
    shared = _kernel_receipt("identical deterministic receipt")
    results, counters = _run_kernel_gated_mixed_race(
        store, shared, shared, winner_role="fallback", monkeypatch=monkeypatch)
    assert results == {"winner": "WIN", "loser": "WIN"}
    assert counters["link"] == {"primary": 0, "fallback": 1}
    _assert_exact_kernel_final(store, shared, tmp_path)


def _mixed_race(store, receipts):
    real_link = core_mod.os.link
    tl = threading.local()
    capability_lock = threading.Lock()
    capabilities = []

    def link(src, dst):
        if getattr(tl, "fallback", False):
            raise OSError("forced fallback")
        return real_link(src, dst)

    barrier = threading.Barrier(len(receipts))
    wins, conflicts, leaks = [], [], []

    def worker(i):
        role = "fallback" if i % 2 == 0 else "primary"
        tl.fallback = role == "fallback"
        with capability_lock:
            capabilities.append(role)
        barrier.wait()
        try:
            store.save(receipts[i]); wins.append(receipts[i]["receipt_digest"])
        except MicroSocraticError:
            conflicts.append(1)
        except Exception as exc:                        # noqa: BLE001
            leaks.append(type(exc).__name__)

    original = core_mod.os.link
    core_mod.os.link = link
    try:
        with ThreadPoolExecutor(max_workers=len(receipts)) as pool:
            list(pool.map(worker, range(len(receipts))))
    finally:
        core_mod.os.link = original
    return wins, conflicts, leaks, capabilities


def test_kernel_mixed_conflicting_stress(tmp_path):
    receipts = [_kernel_receipt(f"distinct {i}") for i in range(8)]
    for trial in range(10):
        trial_dir = tmp_path / f"kc-{trial}"
        store = MicroSocraticReceiptStore(trial_dir)
        wins, conflicts, leaks, capabilities = _mixed_race(store, receipts)
        assert leaks == []
        assert len(wins) == 1 and len(conflicts) == 7   # kernel error type
        assert capabilities.count("primary") == 4
        assert capabilities.count("fallback") == 4
        stored = MicroSocraticReceiptStore(trial_dir).load(_RID)
        assert verify_kernel_receipt(stored)["receipt_digest"] == wins[0]
        assert _no_artifacts(trial_dir) == [_hashed()]


def test_kernel_mixed_identical_stress(tmp_path):
    receipt = _kernel_receipt("same")
    for trial in range(10):
        trial_dir = tmp_path / f"ki-{trial}"
        store = MicroSocraticReceiptStore(trial_dir)
        wins, conflicts, leaks, capabilities = _mixed_race(
            store, [receipt] * 8)
        assert leaks == [] and conflicts == []
        assert len(wins) == 8                           # all idempotent
        assert capabilities.count("primary") == 4
        assert capabilities.count("fallback") == 4
        assert verify_kernel_receipt(
            store.load(_RID))["receipt_digest"] == receipt["receipt_digest"]
        assert _no_artifacts(trial_dir) == [_hashed()]
