"""
Socratic Dialogues Orchestration System (V1)

Public surface:
  - CEDOrchestrator  — drives the full pipeline
  - SocraticAgent    — stateless reasoning agent
  - FakeProvider     — deterministic provider for testing
  - ProviderRegistry — holds the four provider slots
  - All Pydantic models from .models
"""

from .models import (
    AgentRole,
    AgentTask,
    AgentState,
    AgentMove,
    TaskKind,
    TaskLogEntry,
    DialogPhase,
    EpistemicMarker,
    EpistemicStatus,
    PenaltyFlag,
    ProviderStatus,
    LeaderboardStatus,
    SyncGateStatus,
    ShadowScoringMode,
    SectionName,
    RatificationDecision,
    ObjectionSeverity,
    ScoreBreakdown,
    MicroScore,
    SectionScore,
    DraftScorecard,
    SectionDraft,
    AssembledSection,
    AssembledAnswer,
    RatificationVote,
    FinalSynthesisMode,
    CouncilVerdict,
    CouncilRatificationStatus,
    RatificationVerdict,
    CouncilRatification,
    ShadowScoreHarvest,
    EpistemicLeaderboard,
    ProviderResponse,
    CouncilRoundResult,
    FinalResponse,
    SessionState,
    SECTION_ORDER,
    SCORE_WEIGHTS,
    MAX_RATIFICATION_ROUNDS,
    MAX_LEADERBOARD_HARVEST_TIMEOUT,
    LEADERBOARD_INTERPRETATION_WARNING,
)
from .providers import (
    LLMProvider,
    FakeProvider,
    AnthropicProvider,
    OpenAIProvider,
    LocalProvider,
    ProviderRegistry,
)
from .agent import SocraticAgent, CORE_AGENT_PROMPT
from .role_assignment import assign_primary_roles, socrates_for_session
from .topic import Topic, classify_topic
from .provider_registry import (
    CouncilProviderRegistry,
    LLMProviderAdapter,
    BaseProviderAdapter,
    parse_and_validate_move,
    is_placeholder_key,
    AlwaysOKProvider,
    TimeoutProvider,
    InvalidJSONProvider,
    SchemaErrorProvider,
    RateLimitedProvider,
    MissingKeyProvider,
    ScriptedMockProvider,
    TimeoutScriptedProvider,
    CaveatRatifierProvider,
    BlockingObjectionProvider,
    MINIMUM_PROVIDERS,
    QUORUM_FOR_ASSEMBLY,
    PROVIDER_TIMEOUT_SECONDS,
)
from .ced import CEDOrchestrator
from .conversation import (
    ConversationManager,
    ConversationSession,
    ConversationTurn,
    PublicEpistemicMemory,
    HiddenCedTrace,
    ChatResponse,
    build_full_brief,
    save_conversation_json,
    load_conversation_json,
)
from .live_providers import (
    LiveAnthropicAdapter,
    build_council,
    build_council_registry,
)
from .nvidia_nim_provider import (
    LiveNvidiaNIMAdapter,
    NvidiaNIMRequest,
    CannedNvidiaNIMTransport,
    nvidia_chat_envelope,
)
from .learning_foundation import (
    SocratesPrinciple,
    SocratesConstitution,
    TrainingEligibility,
    LearningTrace,
    LearningDataset,
    LearningUse,
    LearningSignalKind,
    PreferenceExample,
    EvalExample,
    EvalVerifierType,
    assess_training_eligibility,
    build_preference_example,
    sanitize_public_payload,
    jsonl,
)
from .learning_trace_collector import (
    ProviderMeta,
    collect_learning_dataset,
    collect_task_traces,
    collect_ratification_traces,
    collect_score_traces,
    infer_provider_family,
    provider_catalog,
    learning_export_summary,
)
from .learning_preference_miner import (
    PreferenceSignal,
    PreferenceMiningMode,
    PreferenceMiningPolicy,
    TracePreferenceScore,
    MinedPreferenceCandidate,
    PreferenceMiningReport,
    score_trace_for_preference,
    mine_preference_candidates,
    mine_preferences,
    smart_learning_summary,
)
from .learning_process_miner import (
    ProcessSignal,
    ProcessMiningMode,
    ProcessMiningPolicy,
    ProcessStepScore,
    ProcessTransition,
    ProcessSFTExample,
    ProcessMiningReport,
    score_process_step,
    mine_process_transitions,
    mine_process_examples,
    process_reward_summary,
)
from .learning_alignment_exporter import (
    AlignmentFormat,
    DatasetSplit,
    ExportedArtifact,
    AlignmentDatasetManifest,
    AlignmentExportPack,
    stable_hash,
    jsonl_lines,
    dedupe_records,
    deterministic_split,
    trace_sft_records,
    dpo_records,
    nemo_dpo_records,
    reward_pair_records,
    process_sft_records,
    build_alignment_export_pack,
    alignment_export_summary,
)
from .learning_quality_gates import (
    QualitySeverity,
    QualityVerdict,
    QualityGatePolicy,
    QualityIssue,
    ArtifactQualitySummary,
    DatasetQualityReport,
    jaccard_similarity,
    check_artifact_integrity,
    check_record_shapes,
    check_split_leakage,
    check_dataset_volume,
    evaluate_quality_gates,
    quality_gate_summary,
)
from .learning_training_planner import (
    TrainingFamily,
    TrainingReadiness,
    DryRunMode,
    TrainingPlannerPolicy,
    TrainingJobPlan,
    TrainingDryRunPlan,
    plan_family,
    build_training_dry_run_plan,
    dry_run_plan_summary,
)
from .learning_dry_run_cli import (
    infer_alignment_format,
    infer_dataset_split,
    load_alignment_pack_from_mapping,
    load_alignment_pack_from_directory,
    run_local_dry_run,
    run_local_dry_run_from_directory,
    build_arg_parser,
    main as learning_dry_run_main,
)
from .self_improvement import (
    SeatHealthTracker,
    EpistemicLessonStore,
    Lesson,
    ProcessLesson,
    TopicSkillTracker,
    CalibrationLedger,
    extract_lesson,
    distill_lesson_with_council,
    review_process_with_council,
    rank_lessons_with_council,
)
from .living_system import (
    OpenQuestionLedger,
    OpenQuestion,
    consolidate_lessons,
    compute_vitals,
    run_inquiry_cycle,
)

__all__ = [
    "AgentRole", "AgentTask", "AgentState", "AgentMove",
    "TaskKind", "TaskLogEntry",
    "DialogPhase", "EpistemicMarker", "EpistemicStatus",
    "PenaltyFlag", "ProviderStatus", "LeaderboardStatus", "SyncGateStatus",
    "ShadowScoringMode",
    "SectionName", "RatificationDecision", "ObjectionSeverity",
    "ScoreBreakdown", "MicroScore", "SectionScore", "DraftScorecard",
    "SectionDraft", "AssembledSection", "AssembledAnswer",
    "RatificationVote", "ShadowScoreHarvest", "EpistemicLeaderboard",
    "FinalSynthesisMode", "CouncilVerdict", "CouncilRatificationStatus",
    "RatificationVerdict", "CouncilRatification",
    "ProviderResponse", "CouncilRoundResult",
    "CouncilProviderRegistry", "LLMProviderAdapter", "BaseProviderAdapter",
    "parse_and_validate_move", "is_placeholder_key",
    "AlwaysOKProvider", "TimeoutProvider", "InvalidJSONProvider",
    "SchemaErrorProvider", "RateLimitedProvider", "MissingKeyProvider",
    "ScriptedMockProvider", "TimeoutScriptedProvider",
    "CaveatRatifierProvider", "BlockingObjectionProvider",
    "MINIMUM_PROVIDERS", "QUORUM_FOR_ASSEMBLY", "PROVIDER_TIMEOUT_SECONDS",
    "FinalResponse", "SessionState",
    "SECTION_ORDER", "SCORE_WEIGHTS", "MAX_RATIFICATION_ROUNDS",
    "MAX_LEADERBOARD_HARVEST_TIMEOUT", "LEADERBOARD_INTERPRETATION_WARNING",
    "LLMProvider", "FakeProvider", "AnthropicProvider",
    "OpenAIProvider", "LocalProvider", "ProviderRegistry",
    "SocraticAgent", "CORE_AGENT_PROMPT",
    "assign_primary_roles", "socrates_for_session",
    "Topic", "classify_topic",
    "CEDOrchestrator",
    "ConversationManager", "ConversationSession", "ConversationTurn",
    "PublicEpistemicMemory", "HiddenCedTrace", "ChatResponse",
    "build_full_brief", "save_conversation_json", "load_conversation_json",
    "LiveAnthropicAdapter", "LiveNvidiaNIMAdapter", "NvidiaNIMRequest",
    "CannedNvidiaNIMTransport", "nvidia_chat_envelope",
    "SocratesPrinciple", "SocratesConstitution", "TrainingEligibility",
    "LearningTrace", "LearningDataset", "LearningUse", "LearningSignalKind",
    "PreferenceExample", "EvalExample", "EvalVerifierType",
    "assess_training_eligibility", "build_preference_example",
    "sanitize_public_payload", "jsonl",
    "ProviderMeta", "collect_learning_dataset", "collect_task_traces",
    "collect_ratification_traces", "collect_score_traces", "infer_provider_family",
    "provider_catalog", "learning_export_summary",
    "PreferenceSignal", "PreferenceMiningMode", "PreferenceMiningPolicy",
    "TracePreferenceScore", "MinedPreferenceCandidate", "PreferenceMiningReport",
    "score_trace_for_preference", "mine_preference_candidates", "mine_preferences",
    "smart_learning_summary",
    "ProcessSignal", "ProcessMiningMode", "ProcessMiningPolicy",
    "ProcessStepScore", "ProcessTransition", "ProcessSFTExample", "ProcessMiningReport",
    "score_process_step", "mine_process_transitions", "mine_process_examples",
    "process_reward_summary",
    "AlignmentFormat", "DatasetSplit", "ExportedArtifact",
    "AlignmentDatasetManifest", "AlignmentExportPack", "stable_hash",
    "jsonl_lines", "dedupe_records", "deterministic_split",
    "trace_sft_records", "dpo_records", "nemo_dpo_records",
    "reward_pair_records", "process_sft_records", "build_alignment_export_pack",
    "alignment_export_summary",
    "QualitySeverity", "QualityVerdict", "QualityGatePolicy", "QualityIssue",
    "ArtifactQualitySummary", "DatasetQualityReport", "jaccard_similarity",
    "check_artifact_integrity", "check_record_shapes", "check_split_leakage",
    "check_dataset_volume", "evaluate_quality_gates", "quality_gate_summary",
    "TrainingFamily", "TrainingReadiness", "DryRunMode", "TrainingPlannerPolicy",
    "TrainingJobPlan", "TrainingDryRunPlan", "plan_family",
    "build_training_dry_run_plan", "dry_run_plan_summary",
    "infer_alignment_format", "infer_dataset_split", "load_alignment_pack_from_mapping",
    "load_alignment_pack_from_directory", "run_local_dry_run",
    "run_local_dry_run_from_directory", "build_arg_parser", "learning_dry_run_main",
    "build_council", "build_council_registry",
    "SeatHealthTracker", "EpistemicLessonStore", "Lesson", "ProcessLesson",
    "TopicSkillTracker", "CalibrationLedger",
    "extract_lesson", "distill_lesson_with_council", "review_process_with_council",
    "rank_lessons_with_council",
    "OpenQuestionLedger", "OpenQuestion", "consolidate_lessons", "compute_vitals",
    "run_inquiry_cycle",
    "run_demo", "build_demo_orchestrator",
]


def __getattr__(name: str):
    """
    Lazily expose the demo helpers without importing the demo module at package
    import time. This keeps `from backend.dialogues import run_demo` working while
    avoiding the double-import RuntimeWarning when running
    `python -m backend.dialogues.demo`.
    """
    if name in ("run_demo", "build_demo_orchestrator"):
        from . import demo
        return getattr(demo, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
